import { Language } from '@/types/translation';

export { Language } from '@/types/translation';

export const LANGUAGES: Language[] = [
  { code: 'auto', name: 'Detect Language', nativeName: 'Auto-detect' },
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'es', name: 'Spanish', nativeName: 'Espanol' },
  { code: 'fr', name: 'French', nativeName: 'Francais' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Portugues' },
  { code: 'pt-BR', name: 'Portuguese (Brazil)', nativeName: 'Portugues do Brasil' },
  { code: 'ca', name: 'Catalan', nativeName: 'Catala' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego' },
  { code: 'eu', name: 'Basque', nativeName: 'Euskara' },
  { code: 'ru', name: 'Russian', nativeName: 'Russkiy' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Ukrayinska' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Balgarski' },
  { code: 'sr', name: 'Serbian', nativeName: 'Srpski' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski' },
  { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenscina' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovencina' },
  { code: 'cs', name: 'Czech', nativeName: 'Cestina' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski' },
  { code: 'ro', name: 'Romanian', nativeName: 'Romana' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi' },
  { code: 'is', name: 'Icelandic', nativeName: 'Islenska' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviesu' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuviu' },
  { code: 'el', name: 'Greek', nativeName: 'Ellinika' },
  { code: 'tr', name: 'Turkish', nativeName: 'Turkce' },
  { code: 'ar', name: 'Arabic', nativeName: 'Al-Arabiyyah' },
  { code: 'he', name: 'Hebrew', nativeName: 'Ivrit' },
  { code: 'fa', name: 'Persian', nativeName: 'Farsi' },
  { code: 'ur', name: 'Urdu', nativeName: 'Urdu' },
  { code: 'hi', name: 'Hindi', nativeName: 'Hindi' },
  { code: 'bn', name: 'Bengali', nativeName: 'Bangla' },
  { code: 'pa', name: 'Punjabi', nativeName: 'Punjabi' },
  { code: 'gu', name: 'Gujarati', nativeName: 'Gujarati' },
  { code: 'mr', name: 'Marathi', nativeName: 'Marathi' },
  { code: 'ta', name: 'Tamil', nativeName: 'Tamil' },
  { code: 'te', name: 'Telugu', nativeName: 'Telugu' },
  { code: 'ml', name: 'Malayalam', nativeName: 'Malayalam' },
  { code: 'kn', name: 'Kannada', nativeName: 'Kannada' },
  { code: 'si', name: 'Sinhala', nativeName: 'Sinhala' },
  { code: 'th', name: 'Thai', nativeName: 'Thai' },
  { code: 'lo', name: 'Lao', nativeName: 'Lao' },
  { code: 'km', name: 'Khmer', nativeName: 'Khmer' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tieng Viet' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu' },
  { code: 'fil', name: 'Filipino', nativeName: 'Filipino' },
  { code: 'tl', name: 'Tagalog', nativeName: 'Tagalog' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'am', name: 'Amharic', nativeName: 'Amarigna' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti' },
  { code: 'zh', name: 'Chinese', nativeName: 'Zhongwen' },
  { code: 'ja', name: 'Japanese', nativeName: 'Nihongo' },
  { code: 'ko', name: 'Korean', nativeName: 'Hangugeo' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Mongol' },
  { code: 'ne', name: 'Nepali', nativeName: 'Nepali' },
  { code: 'my', name: 'Myanmar (Burmese)', nativeName: 'Myanmar' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Qazaqsha' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Uzbek' },
  { code: 'ka', name: 'Georgian', nativeName: 'Kartuli' },
  { code: 'hy', name: 'Armenian', nativeName: 'Hayastani' },
  { code: 'xh', name: 'Xhosa', nativeName: 'IsiXhosa' },
  { code: 'zu', name: 'Zulu', nativeName: 'IsiZulu' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yoruba' },
  { code: 'ig', name: 'Igbo', nativeName: 'Igbo' },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa' },
  { code: 'ceb', name: 'Cebuano', nativeName: 'Cebuano' },
];

export const getLanguageByCode = (code: string): Language | undefined => {
  return LANGUAGES.find(lang => lang.code === code);
};

export const getLanguageName = (code: string): string => {
  const language = getLanguageByCode(code);
  return language ? language.name : code;
};